# Generated by Django 3.2.6 on 2024-10-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='phone',
        ),
    ]
